gfjfgj

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -5,35 +5,31 @@ name: Python application
 
 on:
   # on: [push, pull_request, workflow_dispatch]
-  # create:
-  #   tags:
-  #   - 'v[0-9]+.[0-9]+.[0-9]+*'
   push:
-    branches: [ main ]
+    #branches: [ main ]
+    branches:
+      - main
+      - '*.x'
+    paths-ignore:
+      - 'docs/**'
+      - '*.md'
+      - '*.rst'
     tags:
     - 'v[0-9]+.[0-9]+.[0-9]+*'
     #tags: ['v[0-9].[0-9]+.[0-9]+*'] 
   pull_request:
-    branches: [ main ]
+    #branches: [ main ]
+    branches:
+      - main
+      - '*.x'
+    paths-ignore:
+      - 'docs/**'
+      - '*.md'
+      - '*.rst'
+    tags:
+    - 'v[0-9]+.[0-9]+.[0-9]+*'
+    #tags: ['v[0-9].[0-9]+.[0-9]+*']
   workflow_dispatch:
-#    inputs:
-#      logLevel:
-#        description: 'Log level'
-#        required: true
-#        default: 'warning'
-#        type: choice
-#        options:
-#        - info
-#        - warning
-#        - debug
-#      tags:
-#        description: 'Test scenario tags'
-#        required: false
-#        type: boolean
-#      environment:
-#        description: 'Environment to run tests against'
-#        type: environment
-#        required: true
 #  schedule:
 #    - cron: '30 5,17 * * *'
 #    - cron: '30 5 * * 1,3'
@@ -140,47 +136,72 @@ jobs:
 #   * nashmaniac/create-issue-action@v1.1: creates issue for repo
 #   * peter-evans/commit-comment@v1: adds message to commit
 # **************************************************************************************************************** #
+#
+#    - name: pytester-cov
+#      id: pytester-cov
+#      uses: alexanderdamiani/pytester-cov@v1.2.3
+#      with:
+#        pytest-root-dir: '.'
+#        cov-omit-list: 'test_*.py, run.py'
+#        cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
+#        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+#
+#    - name: Coverage single fail - new issue
+#      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+#      uses: nashmaniac/create-issue-action@v1.1
+#      with:
+#        title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
+#        token: ${{secrets.GH_GITHUB_TOKEN}}
+#        assignees: ${{github.actor}}
+#        labels: worflow-failed
+#        body: ${{ steps.pytester-cov.outputs.output-table }}
+#
+#    - name: Coverage single fail - exit
+#      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
+#      run: |
+#        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
+#        exit 1
+#    - name: Coverage total fail - new issue
+#      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+#      uses: nashmaniac/create-issue-action@v1.1
+#      with:
+#        title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
+#        token: ${{secrets.GH_GITHUB_TOKEN}}
+#        assignees: ${{github.actor}}
+#        labels: worflow-failed
+#        body: ${{ steps.pytester-cov.outputs.output-table }}
+#
+#    - name: Coverage total fail - exit
+#      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
+#      run: |
+#        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+#        exit 1
+#    - name: Commit pytest coverage table
+#      uses: peter-evans/commit-comment@v1
+#      with:
+#        body: ${{ steps.pytester-cov.outputs.output-table }}
 
-    - name: pytester-cov
-      id: pytester-cov
-      uses: alexanderdamiani/pytester-cov@v1.2.3
-      with:
-        pytest-root-dir: '.'
-        cov-omit-list: 'test_*.py, run.py'
-        cov-threshold-single: ${{ env.COVERAGE_SINGLE }}
-        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+# **************************************************************************************************************** #
 
-    - name: Coverage single fail - new issue
-      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
-      uses: nashmaniac/create-issue-action@v1.1
-      with:
-        title: Pytest coverage single falls below minimum ${{ env.COVERAGE_SINGLE }}
-        token: ${{secrets.GH_GITHUB_TOKEN}}
-        assignees: ${{github.actor}}
-        labels: worflow-failed
-        body: ${{ steps.pytester-cov.outputs.output-table }}
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v1
 
-    - name: Coverage single fail - exit
-      if: ${{ steps.pytester-cov.outputs.cov-threshold-single-fail == 'true' }}
-      run: |
-        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-single-fail }}"
-        exit 1
-    - name: Coverage total fail - new issue
-      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
-      uses: nashmaniac/create-issue-action@v1.1
-      with:
-        title: Pytest coverage total falls below minimum ${{ env.COVERAGE_TOTAL }}
-        token: ${{secrets.GH_GITHUB_TOKEN}}
-        assignees: ${{github.actor}}
-        labels: worflow-failed
-        body: ${{ steps.pytester-cov.outputs.output-table }}
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v1
 
-    - name: Coverage total fail - exit
-      if: ${{ steps.pytester-cov.outputs.cov-threshold-total-fail == 'true' }}
-      run: |
-        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
-        exit 1
-    - name: Commit pytest coverage table
-      uses: peter-evans/commit-comment@v1
+    - name: Docker Login
+      uses: docker/login-action@v1
       with:
-        body: ${{ steps.pytester-cov.outputs.output-table }}
+        username: ${{secrets.DOCKERHUB_USERNAME}}
+        password: ${{secrets.DOCKERHUB_TOKEN}}
+
+    - name: Build and push Docker images
+      uses: docker/build-push-action@v2
+      with:
+        push: true
+        context: .
+        tags: |
+          chrismarsilva/cms-python-jenkins:latest
+          chrismarsilva/cms-python-jenkins:${{github.run_number}}
+
+# **************************************************************************************************************** #
